/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leili_season1_jni_activity_JNIActivity */

#ifndef _Included_com_leili_season1_jni_activity_JNIActivity
#define _Included_com_leili_season1_jni_activity_JNIActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leili_season1_jni_activity_JNIActivity
 * Method:    say
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leili_season1_jni_activity_JNIActivity_say
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
